server {
    listen 80;
    server_name tedros.test www.tedros.test localhost;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl http2;
    server_name tedros.test www.tedros.test localhost;

    ssl_certificate /etc/nginx/ssl/tedros.test+4.pem;
    ssl_certificate_key /etc/nginx/ssl/tedros.test+4-key.pem;

    location / {
        proxy_pass                http://tomee_cluster/tedros-io/;
        proxy_set_header          Host $host;
        proxy_set_header          X-Real-IP $remote_addr;
        proxy_set_header          X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header          X-Forwarded-Proto $scheme;
        proxy_buffering           off;
    }

    # EJB endpoint mapped specifically for Java client to use HTTPS
    location /tomee/ {
        proxy_pass                http://tomee_cluster/tomee/;
        proxy_set_header          Host $host;
        proxy_set_header          X-Real-IP $remote_addr;
        proxy_set_header          X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header          X-Forwarded-Proto $scheme;
        proxy_buffering           off;
    }
}
